### ISSUE TITLE
No audio feature in tsclientlib

### ISSUE THREAD

**Issue by matthew-jones-uk** [ReSpeak/tsclientlib#10]
Running the audio example returns that there's no feature. Not sure if I'm doing something wrong?

```
[matthew@laptop tsclientlib]$ cargo run --features audio --example audio
error: Package `tsclientlib v0.1.0 (/home/matthew/Projects/tsbot/tsclientlib/tsclientlib)` does not have these features: `audio`
```

**Comment by Flakebi** [comment]
You did nothing wrong, I forgot to update the readme and the audio example. Previously I was using gstreamer for audio but there always was some stuttering so I switched to SDL.

The example is now using SDL too, so `cargo run --example audio` should work.

**Comment by matthew-jones-uk** [comment]
Tried the example and it worked great. Thanks for the quick reply and the extra info.
