### ISSUE TITLE
RUSTSEC-2020-0018: crate has been renamed to `block-cipher`

### ISSUE THREAD

**Issue by tyranron** [ReSpeak/tsclientlib#16]
> crate has been renamed to `block-cipher`

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `block-cipher-trait`                      |
| Version             | `0.6.2`                   |
| URL                 | [https://github.com/RustCrypto/traits/pull/139](https://github.com/RustCrypto/traits/pull/139) |
| Date                | 2020-05-26                         |

This crate has been renamed from `block-cipher-trait` to `block-cipher`.

The new repository location is at:

&lt;https://github.com/RustCrypto/traits/tree/master/block-cipher&gt;

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2020-0018.html) for additional details.

**Comment by tyranron** [comment]
Seems to be resolved if bumping up crypto dependencies like `aes` to newer versions.

**Comment by Flakebi** [comment]
Thanks for the note.
I planned to update the `eax` crate anyway, I guess now is the time to do so.

**Comment by Flakebi** [comment]
eax is updated and now part of the RustCrypto crates.
