### ISSUE TITLE
Change license from OSL to MIT/Apache

### ISSUE THREAD

**Issue by Flakebi** [ReSpeak/tsclientlib#17]
Hi,
I think it might be a good idea to license these crates under the MIT/Apache 2.0 licenses, as these are widely used throughout the Rust library ecosystem.
To do so, I need your agreement to use/relicense your contributions under MIT/Apache 2.0, as you contributed to this project under OSL.

- [x] @Jokler
- [x] @tyranron

Are you ok with this change?

**Comment by tyranron** [comment]
@Flakebi me is totally OK.

As a side note: what do you think about BlueOak-1.0.0 license?

**Comment by Jokler** [comment]
Yes, I agree to re-licensing my code under MIT/Apache 2.0.

**Comment by Flakebi** [comment]
Thanks a lot, done in 5e4eb23.

> As a side note: what do you think about BlueOak-1.0.0 license?

Sounds interesting, I didn’t hear of that before, so thanks for the note. This article of the author sounds really great, it’s an utopia unfortunately: https://writing.kemitchell.com/2019/03/17/License-Utopia.html
I think the MIT/Apache combination is still a nice fit for Rust libraries because a great part of Rust libraries out there are using these.
