### ISSUE TITLE
How to subscribe to new channels?

### ISSUE THREAD

**Issue by Jokler** [ReSpeak/tsclientlib#18]
I saw that `tsclientlib::data::Server` has a `set_subscribed` method but it seems overkill to call that every time a channel is created.

Is another such subscribe method missing from `tsclientlib::data::Channel` or did I just miss it?

**Comment by Jokler** [comment]
It looks like `set_subscribed` on `tsclientlib::data::Server` doesn't do anything for new channels anyway.

**Comment by Splamy** [comment]
From what I see, the normal ts3 client also just does exactly this. Manually set subscribe when a new channel is created.

```ini
[IN ] notifychannelcreated cid=12 cpid=3 channel_name=new channel_codec_quality=6 channel_order=0 channel_codec_is_unencrypted=1 channel_flag_maxfamilyclients_unlimited=0 channel_flag_maxfamilyclients_inherited=1 invokerid=2 invokername=Splamy invokeruid=Splamy36QrG5AkF4uoS\/h0fpHr0=
[IN ] notifyclientleftview cfid=5 ctid=12 reasonid=1 invokerid=0 invokername=Server clid=2
[OUT] channelsubscribe cid=12 return_code=1:3
[IN ] notifycliententerview cfid=0 ctid=12 reasonid=2 clid=2 client_unique_identifier=Splamy36QrG5AkF4uoS\/h0fpHr0= client_nickname=Splamy client_input_muted=0 client_output_muted=0 client_outputonly_muted=0 client_input_hardware=1 client_output_hardware=1 client_meta_data client_is_recording=0 client_database_id=150 client_channel_group_id=5 client_servergroups=6,7 client_away=0 client_away_message client_type=0 client_flag_avatar=fe9e810e669712e7f73654b1379e9fe4 client_talk_power=75 client_talk_request=0 client_talk_request_msg client_description client_is_talker=0 client_is_priority_speaker=0 client_unread_messages=0 client_nickname_phonetic client_needed_serverquery_view_power=75 client_icon_id=0 client_is_channel_commander=0 client_country client_channel_group_inherited_channel_id=12 client_badges=Overwolf=0 client_myteamspeak_id client_integrations client_myteamspeak_avatar client_signed_badges
[IN ] notifychannelsubscribed cid=12
[IN ] error id=0 msg=ok return_code=1:3
```

Sooner or later we definitely want to add a set_subscribed per channel, but right now as you said there's no method yet.
set_subscribed(bool) on the server sends out a `channelsubscribeall` which is a bit overkill to call for each channel, but it should work.
since set_subscribed returns a command you'll have to call send on it:
https://github.com/ReSpeak/tsclientlib/blob/5fbef849953e896d1cc725f9da5b0300d1764100/tsclientlib/examples/channeltree.rs#L86

(Sidenote: Flakebi, the lead maintainer of this project, is on vacation for two weeks right now. I'm not as versed with the project so I can only give basic help)

**Comment by Jokler** [comment]
Oh, I did indeed not realize that I had to send the message after, maybe it would be possible to give a warning if it is unused? Not sure if that was stabilized for all types.

For now I'll just subscribe to all until a better solution comes up.
I might have a look at creating the per channel method later but no promises.

**Comment by Splamy** [comment]
we would probably implement this with our book2message declarations. I can take a look into that.

> maybe it would be possible to give a warning if it is unused

`#[must_use]` seems stable as far as I see. I'll keep in in mind and ask flakebi on the next occasion

**Comment by Splamy** [comment]
Okay i added `set_subscribed` on channels. You'll have to call it the same way as on the server and send it.
I also added the `#[must_use]` annotation as suggested. You should now get a warning when unused :)

```rust
con.get_state().unwrap().channels.get(&ChannelId(13)).unwrap().set_subscribed(true).send(&mut con)?;
```

**Comment by Jokler** [comment]
Alright, sounds good.

I'll have to update the git version I am tracking, then I'll incorporate it.

**Comment by Bluscream** [comment]
@Jokler where are you using this lib?

**Comment by Jokler** [comment]
https://github.com/Mavulp/pokebot

**Comment by Flakebi** [comment]
He, this issue was not yet fixed :)
Now it works. After subscribing the server, tsclientlib will automatically subscribe new channels.

**Comment by Jokler** [comment]
Oh, my bad, my initial question was solved by the `set_subscribed` method on channel, but I guess this way it's easier.
