### ISSUE TITLE
Reconnect using the same Connection

### ISSUE THREAD

**Issue by Jokler** [ReSpeak/tsclientlib#19]
Is it possible to reconnect after the connection was lost using the same instance of `Connection` or does a new one have to be created?

**Comment by Flakebi** [comment]
You need to create a new `Connection` for this.
Ideally, the `Connection` would automatically reconnect after the connection is lost. Currently it only tries a single time, I did not yet get around to implement this properly.

**Comment by Flakebi** [comment]
Reconnecting automatically is now implemented in a better way (be95e02fe78c49685ed798f4a814c7e0ca8641af):

If a connection times out after it connected successfully, tsclientlib waits for 10s and then tries to reconnect. As long as no response is received (i.e. reconnecting fails with a timeout), it tries again. When another error is received, e.g. socket cannot be opened or the server responds with an error, connecting is aborted.

**Comment by Jokler** [comment]
I've noticed that this still doesn't let me reconnect after a server shutdown. This means that if a server gets restarted the client would just stay disconnected.

**Comment by Flakebi** [comment]
Right, I only considered timeouts. That should be fairly easy to add.
