### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by lexesv** [ReSpeak/tsclientlib#2]
```
error[E0432]: unresolved import `tsproto::errors`
  --> tsproto-commands/src/codec.rs:10:14
   |
10 | use tsproto::errors::Error;
   |              ^^^^^^ Could not find `errors` in `tsproto`

warning: unreachable statement
  --> tsproto-commands/src/codec.rs:57:4
   |
57 |    let header = Header::new(PacketType::Command);
   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unreachable_code)] on by default

error: aborting due to previous error

error: Could not compile `tsproto-commands`.
```

**Comment by Flakebi** [comment]
This is a known issue, the library is currently still a work in progress and not usable, I will add a note to the readme.

**Comment by Flakebi** [comment]
Follow-up note: The library and all examples are compiling and working again, though there is still not much more possible than connecting to a server and disconnecting again.
(Connecting will not yet work for the TeamSpeak server ≥ 3.1 as the protocol changed)

In a few days I will finally have free time again so there will be more progress.
