### ISSUE TITLE
Breaking Changes

### ISSUE THREAD

**Issue by Flakebi** [ReSpeak/tsclientlib#25]
This issue is used to announce breaking changes when they are pushed.

cc @0xpr03

**Comment by Flakebi** [comment]
6e8e5b3b14aec1d6e422b6de65af1e96b235b582 Replace `slog` with `tracing`

**Comment by 0xpr03** [comment]
ah nice, then I can drop 5 crates :)

**Comment by Jokler** [comment]
The thread locality makes it difficult for me to understand how to link spans to sections of code for me. It seems like each thread has one span at a time instead of each piece of code having one logger to me but I might be wrong.
