### ISSUE TITLE
tsclientlib with WebAssembly on the web

### ISSUE THREAD

**Issue by skhalymon** [ReSpeak/tsclientlib#29]
Hey @Flakebi! I'm checking possibilities of creating a small subset of the TS client for the web. Seems using a tsclientlib and WebAssembly for that should be a good way to go. I'm curious, have you tried to compile it for the web? Do you see some limitations in achieving such scenario? Thanks

**Comment by Flakebi** [comment]
Hi, web browsers don’t allow opening UDP connections (for good reasons), so running a stand-alone TS client in a browser is impossible unfortunately. You would need some kind of proxy on a server or locally on a pc that acts as the UDP server/client and somehow transfers the packets to the browser.

There’s also a few places in tsclientlib that won’t compile to WebAssembly, the UDP code obviously, the dns resolver code and the server nickname resolving. Apart from these, it should compile but due to browser restrictions with limited use.

**Comment by skhalymon** [comment]
For now, we see few solutions that could be used:
1) Create separate apps using flutter and rust
2) Create proxy server which would communicate with fronted and teamsapeak server ( Frontend  <-WebRTC-> Proxy server <-TCP\UDP-> Teamspeak)

**Comment by Splamy** [comment]
Regarding 2.; we already have a fully working high-level proxy which is doing exactly that for our own full ts3 client app with a web frontend.
However that project is currently not open source yet, but maybe we could give you access if you'd be interested and Flakebi approves.
Flakebi is currently on vacation right now so I don't know how soon he could answer.

**Comment by skhalymon** [comment]
It's quite interesting that you already have such solution! I would like to check it if it is possible. 

Have you checked latency of this solution with proxy? Let me give you a little context of what we try to achieve.

We want to do is creating a simplified version of interface for interpreters of [Creative Society project](https://creativesociety.com/). We would like to simplify the interface to be able to decrease the amount of time for setup of new interpreters. And improve general usability of solution for interpreters.

Currently, it takes a lot of time for volunteers of Creative Society to set up all software and teach how to use it. And count that we have more than 100 languages now, this process is quite hard.

So, the basic idea is having a simple interface where no need to install Teamspeak and which would work both on mobile and desktop.

We're already using your tsclientlib library in [Ephyr restreamer](https://github.com/ALLATRA-IT/ephyr/tree/master/components/restreamer) which is used for streams and quite pleased of it!

**Comment by skhalymon** [comment]
@Splamy @Flakebi ping :)

**Comment by Splamy** [comment]
Hey there sorry for the late response.
Flakebi has pointed out to me that I probabyl misread what you need.
Our proxy handles everything _except_ audio data to the frontend. Our rationale was that this would give the best audio experience for a desktop app; so I don't know how useful this would still be to you

**Comment by skhalymon** [comment]
Ok then, seems we can close the issue. Thanks for your pleasure help!

**Comment by skhalymon** [comment]
Hey @Flakebi @Splamy !

I'm checking options to proxy connection from the ts client to multiple ts servers based on channel name. While I'm digging into protocol, I'm curious, do you have plans to open source your proxy solution? Thanks!
