### ISSUE TITLE
Copyright & Teamspeak

### ISSUE THREAD

**Issue by 0xpr03** [ReSpeak/tsclientlib#3]
Hello,
I'd like to use this lib as I'm currently sandboxing teamspeak in docker for a music-bot application I'm developing with some other people, which is really painful in terms of overhead and performance.
But I've to ask about the big elephant in the room: How lawyer proof is this reverse engineering of teamspeaks client API ? Specifically as the official SDK can't be used on teamspeaks on servers.

**Comment by Flakebi** [comment]
Hi,
I’m am not a lawyer and I know little about the laws for reversing so I can not give any legal advice.

However, I can share some thoughts we have on this. The TeamSpeak [protocol](https://github.com/ReSpeak/tsdeclarations/blob/master/ts3protocol.md) and a [popular bot](https://github.com/Splamy/TS3AudioBot) implementing it are around for quite a few years now and there has been no action of TeamSpeak against it.
Also, TeamSpeak is earning its money through selling servers, the client is free. So as long as you don’t publish your own server, the chance that TS bothers should be very low in my opinion.

And a short note for the legal side: None of our projects contains any code copied from TeamSpeak,  which would be a problem with copyright.

PS: If you are looking for a music bot, you might want to take a look at https://github.com/Splamy/TS3AudioBot :)

**Comment by 0xpr03** [comment]
Hi thanks for the answer.
Unfortunately we've started developing the bot before we knew of your application.
So we already have a full rust backend that's possible to control with a frontend written in any language that speaks http-REST. And we plan on developing it further ahead, so take this as a non-aggressive greeting from your competition, if OSS can have such a thing ;)
