### ISSUE TITLE
Problems with sending a message

### ISSUE THREAD

**Issue by painerp** [ReSpeak/tsclientlib#33]
Hi,
Firstly, I would like to mention that I am fairly new to Rust and using this library, so please bear with me if I have overlooked something obvious.

I tried using this library to send a message back to my client or the channel, like a simple help command. I anticipated this to be a straightforward process, but I'm having difficulty making it work.

Here's what my code looks like:
```rust
let state = con.get_state().unwrap_or_else(|e| {
   error!("Unable to get state: {}", e);
   exit(-1);
});

match state.send_message(MessageTarget::Channel, "test").send(&mut con) {
  Ok(_) => info!("Message sent"),
  Err(e) => error!("Message sending error: {}", e),
};
```

The connection appears to be functional, as I can successfully change the bot's username. Additionally, the "Message sent" line is printed, suggesting that no errors were returned.

I also tried cloning the SimpleBot repository to see if it works, but it doesn't respond to any commands I issue. As a result, I am unsure whether the issue lies with my Teamspeak Server or the library itself.

I would greatly appreciate any assistance in debugging this further.

Thanks!

**Comment by Flakebi** [comment]
Hi,
I assume you use the async version (not the `SyncConnection`)?

`.send(&mut con)` puts a message into the send queue, but it doesn’t wait until the message is sent and acknowledged by the server (which would be blocking).
To make sure that happens, you need to poll on `con.events()`, like e.g. here or after the disconnect in the same file: https://github.com/ReSpeak/tsclientlib/blob/master/tsclientlib/examples/simple.rs#L59

**Comment by painerp** [comment]
Thank you so much for your assistance! It appears I had overlooked that aspect. I've managed to get it working in the example script now. I was just puzzled when I noticed that the SimpleBot also didn't return any responses but that's probably also on me.
