### ISSUE TITLE
Big ping issue

### ISSUE THREAD

**Issue by vedran77** [ReSpeak/tsclientlib#35]
Why does my bot have like 50000-70000 ping?

**Comment by Flakebi** [comment]
I find it hard to say anything with almost no information.

1. What is “my bot”? (Are you sure this is something using tsclientlib?)
2. What unit are these numbers in? (seconds, milliseconds, nanoseconds?)
3. From where to where is your bot connecting? (to localhost? to a server far away? what is your ping to that server?)

**Comment by vedran77** [comment]
Yap you are right, I didn't say anything so...

I used this example https://github.com/ReSpeak/tsclientlib/blob/master/tsclientlib/examples/audio.rs and connected it to my Teamspeak server(based in Germany somewhere I think) (bot is started it from my computer, and I'm also connected to the server).

Teamspeak have the ability to check client connection info (right-click on the user to get some data about his connection)
So I checked my Teamspeak bot(tsclientlib) and it has 50000ms-70000ms. 

If you need any additional data I can provide everything.

**Comment by Flakebi** [comment]
It works fine for me. See the attached screenshot for an example. The client that is shown is the tsclientlib audio example and it has a ping of 24 ms, which is about the same ping I get when pinging the server.

![2023-09-23](https://github.com/ReSpeak/tsclientlib/assets/6499211/4e10e680-15ef-47bd-9213-96d8cb9ecafd)

**Comment by Bluscream** [comment]
Also keep in mind that the generation of the data in this window is up to the client so the values can be off by any number of reasons not related to the network.

**Comment by vedran77** [comment]
You are right, the ping is normal but it's like float, my ping was 50 for example and the ping on the bot is 50.881 so I thought that it was 50881, not 50.881, it's my bad.
