### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by 0xpr03** [ReSpeak/tsclientlib#4]
Are there any plans to release this to crates.io ?
Would make it more convenient to embed in cargo.toml

**Comment by Flakebi** [comment]
I plan to publish these libraries on crates.io at some point, though in my opinion this makes more sense when the api is stable and I don’t have to break semver regularly.
The api should be rather stable now so no big changes but there are some essential features missing which may change the api.

For example the identity level is hardcoded to 8 and I want to rewrite the audio part at one point (it is somehow working but over internet, people here stuttering and it needs a gstreamer plugin).

I guess the best way to use it for now is linking the git repo and fixing a commit with `rev = "…"`.

**Comment by 0xpr03** [comment]
You don't have to break semver as long as you stay in 0.X, where it's allowed to make breaking changes.
I'm using gstreamer internally, in my head you'd just have to copy stuff from the gst-sink to the audio network api via futures, every time there's more data.

**Comment by Flakebi** [comment]
You’re right, semver does not require it (though cargo expects it). I will consider publishing the crates to crates.io.

Ok interesting, I tried to do that with gstreamer. So far I did not look into that issue so it might also be a problem with the TS client. For reference, the gstreamer code is here: https://github.com/ReSpeak/tsclientlib/blob/master/utils/tsproto-audio/src/audio_to_ts.rs#L130

**Comment by 0xpr03** [comment]
> You’re right, semver does not require it (though cargo expects it).

Yeah, which is why you're supposed to ping 0.X instead of 0.
 
> Ok interesting, I tried to do that with gstreamer. So far I did not look into that issue so it might also be a problem with the TS client. For reference, the gstreamer code is here: https://github.com/ReSpeak/tsclientlib/blob/master/utils/tsproto-audio/src/audio_to_ts.rs#L130

I'll have to look into that.
Otherwise I can recommend asking @sdroege aka slomo (also on #gstreamer in freenode) for more help, he knows gst inside out.

**Comment by Flakebi** [comment]
I finally finished publishing the crates. This means [tsclientlib](https://docs.rs/tsclientlib/0.1.0/tsclientlib/) is now available on crates.io :).
