### ISSUE TITLE
Build fails on latest after removal of utils/ffigen

### ISSUE THREAD

**Issue by snaiperskaya96** [ReSpeak/tsclientlib#6]
Hello, it's annoying me again!

Building the lib from scratch fails as tsclientlib-ffi is always built but it has a broken build dependency (utils/ffigen) which has been removed recently (https://github.com/ReSpeak/tsclientlib/commit/40f5f3b74a76e18b4faa0b2666670add9fcc54b5).

For now i'm falling back to the previous commit :)

**Comment by Flakebi** [comment]
Thanks for the heads up!
I removed the outdated tsclientlib-ffi project too, so it should build again.
