### ISSUE TITLE
Building failed, tokio2 missing 'tokio02::io::AsyncWriteExt' and 'tokio02::io::AsyncWriteExt'

### ISSUE THREAD

**Issue by jn4kr** [ReSpeak/tsclientlib#8]
Hi,
the build failed with the following error:
``` 
$ cargo build
   Compiling tsclientlib v0.1.0 (/home/jnk/projects/tsclientlib/tsclientlib)
error[E0432]: unresolved import "tokio02::net::TcpStream"
  --> tsclientlib/src/lib.rs:30:5
   |
30 | use tokio02::net::TcpStream;
   |     ^^^^^^^^^^^^^^^^^^^^^^^ no "TcpStream" in "net"

error[E0432]: unresolved import "tokio02::io::AsyncWriteExt"
  --> tsclientlib/src/lib.rs:31:5
   |
31 | use tokio02::io::AsyncWriteExt;
   |     ^^^^^^^^^^^^^-------------
   |     |            |
   |     |            help: a similar name exists in the module: "AsyncWrite"
   |     no "AsyncWriteExt" in "io"

error: aborting due to 2 previous errors

For more information about this error, try "rustc --explain E0432".
error: could not compile "tsclientlib".

To learn more, run the command again with --verbose. 
```

For me personally it was resolved by adding `features = ["full"]` to tokio2 declaration in tsclientlib/Cargo.toml

Is that the correct way to handle it, or am i overseeing something else? (Relatively new to Rust)

Edit 1: Formatting

**Comment by Flakebi** [comment]
Hi,
thanks for the report, yes `features = ["full"]` should fix the compilation error.
For now I completely reverted the commit introducing tokio 0.2 because it does not work that well with mixing the different versions.

I’ll leave this issue open for now to remind me to setup a CI.

**Comment by Flakebi** [comment]
CI is up and running, the code should break less often now.
