### ISSUE TITLE
How to upload avatar?

### ISSUE THREAD

**Issue by fkaa** [ReSpeak/tsclientlib#9]
Is there a way to upload avatars currently?

**Comment by Flakebi** [comment]
There is. The `Connection` has a function `upload_file` defined here:
https://github.com/ReSpeak/tsclientlib/blob/e54986b9a7d9d5a662c85ef0fabc2012344cbdc2/tsclientlib/src/lib.rs#L830-L832

You can use it like this:
```rust
// Uid of own client
let uid = {
    let con = connection.lock();
    con.clients[con.own_client].uid.clone()
};
// Channel 0 for icons and avatars
// The avatar uid has a special encoding (hex with digits a-p instead of 0-9a-f)
let fut = connection.upload_file(
    ChannelId(0),
    &format!("/avatar_{}", uid.as_avatar()),
    …
);
// Wait for the future and write into the tcp stream
```


PS: I did not test uploading so far, only downloading, so if it does not work like you expect it, please comment here.
